name: "Bundler Minifier Action"
description: "A Github Action that works like Bundler Minifier into Visual Studio."
branding:
    icon: package
    color: blue
inputs:
    bundle_config_folder:
        description: "Path for bundleconfig (Default: ./test)"
        default: "./test"
        required: false

    create_bundle_config:
        description: "Use search_extensions inputs to search and create a bindleconfig.json automatically (Default: true)"
        default: "true"
        required: false

    search_extensions:
        description: "Which files will be minified (Default: js|css|html)"
        default: "js|css|html"
        required: false

    delete_input_files:
        description: "Delete inputFiles from source project (Default: true)"
        default: "true"
        required: false

runs:
    using: "composite"
    steps:
        - name: Build & Run
          shell: bash
          run: |
              npm install
              node index.js
