name: "Bundler Minifier Action"
description: "A Github Action that works like Bundler Minifier into Visual Studio."
branding:
    icon: package
    color: blue
inputs:
    working_directory:
        description: "Working Directory (Default: ./)"
        default: "./"
        required: false

    bundle_config_folder:
        description: "Path for bundleconfig (Default: ./test)"
        default: "./test"
        required: false

    create_bundle_config:
        description: "Use search_extensions inputs to search and create a bindleconfig.json automatically (Default: true)"
        default: "true"
        required: false

    search_extensions:
        description: "Which files will be minified (Default: js|css|html)"
        default: "js|css|html"
        required: false

    delete_input_files:
        description: "Delete inputFiles from source project (Default: true)"
        default: "true"
        required: false

runs:
    using: "composite"
    steps:
        - name: 🔰 Setup Node.js
          uses: actions/setup-node@v2
          with:
              node-version: 18

        - name: 🔰 Cloning This Action
          uses: actions/checkout@master
          with:
              repository: edelciomolina/bundler-minifier-action
              path: bundler-minifier-action

        - name: 🔰 Installing Dependencies
          shell: bash
          working-directory: bundler-minifier-action
          run: |
              echo "INSTALLING DEPENDENCIES 💠 $(pwd)";
              npm install;

        - name: 🔰 Running Bundler Minifier
          shell: bash
          run: |
              echo "RUNNING MINIFIER 💠 $(pwd)";
              node "bundler-minifier-action/index.js" --bundle-config-folder "${{ inputs.bundle_config_folder }}"  --create-bundle-config "${{ inputs.create_bundle_config }}" --search-extensions "${{ inputs.search_extensions }}" --delete-input-files "${{ inputs.delete_input_files }}";
